### ISSUE TITLE
比如我想改修UEXP中的模型颜色，要怎么做呢

### ISSUE THREAD

**Issue by thriller311** [HaoJun0823/CODEVEIN-Mod-Guide#1]
@HaoJun0823 如题，多谢。困扰了好久，求指点。或加QQ 445831224，非常感谢

**Comment by HaoJun0823** [comment]
模型的修改不在这篇指导书中。
详细的可以访问Discord的社区来了解模型Mod的设计与制作。

**Comment by thriller311** [comment]
也就是说通过UEedit这样的16进制软件，只能改确定数值的属性，其中不确定数值的，暂时还没有好的办法。是吧

**Comment by HaoJun0823** [comment]
在前几周有人实现了一套针对4.18 UE4引擎的数据文件反序列化工具，也可以在社区找到，可以可视化修改。
（其实在我的Stars里，但Github没按时间排序所以我还真找不到了）

**Comment by thriller311** [comment]
我操，那就牛逼了啊，可以直接修改了。我被这个问题困扰的秃完了，梳子都可以不用了。能帮找找吗，大佬。今天第一次学用GitHub，完全小白。还专门买了个VPN。

**Comment by thriller311** [comment]
能帮找找吗，大佬。今天是我第一次用GITHUB，啥都不懂... 这个问题困扰我太久了，头都秃了

**Comment by HaoJun0823** [comment]
https://github.com/KarbonAKitt/CVWiki/wiki/Weapon-Replacement-Guide 模型替换
https://github.com/kaiheilos/Utilities Uasset工具

**Comment by thriller311** [comment]
我看看，太感谢了

**Comment by thriller311** [comment]
尝试了半天，连原有的uasset在UE4下面我都读不出来。能不能这样，我出钱，请你帮我改一下。主要就要改一下模型颜色，全绿全红，还有把一些声音文件改成0分贝的，就可以了，成吗

**Comment by thriller311** [comment]
PUBG(PC)

**Comment by HaoJun0823** [comment]
我做MOD不要钱的.jpg
模型颜色我自己这边不行，因为我的CPU有点小问题导致Blender和UE4之间不太对付……
声音好办，你随便挑一个声音文件，复制然后改名替换原来的文件打包成MOD就可以。

**Comment by thriller311** [comment]
能加你QQ或微信聊吗，多谢大佬。总算找到一个人懂的了
